### ISSUE TITLE
Accounts: Profile page client error

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#1123]
Profile page erroring https://beta.zesty.io/profile/

Preference still works, but base profile fails to load https://beta.zesty.io/profile/preferences/

![image](https://user-images.githubusercontent.com/729972/194378790-b616c27f-de2b-4926-81ab-b48664c6da33.png)

**Comment by glespinosa** [comment]
@ardeay I don't see that error message, maybe that error happens when trying to access the page while the website is still building the new merge?

[screencast-nimbus-capture-2022.10.07-17_29_03.webm](https://user-images.githubusercontent.com/44116036/194521879-c1e84cee-4937-4dfc-b678-e75dae1b0cce.webm)

[screencast-nimbus-capture-2022.10.07-17_31_30.webm](https://user-images.githubusercontent.com/44116036/194522285-22c2d162-f04f-4187-a101-0bc0a4e10682.webm)

**Comment by ardeay** [comment]
![image](https://user-images.githubusercontent.com/729972/194585098-1ff4fe8e-2f70-4661-9550-ab41333acad2.png)

**Comment by ardeay** [comment]
Could it have to do with this bad instance request being made 
![image](https://user-images.githubusercontent.com/729972/194585477-9d97c8e5-abc5-4504-a9e8-bd24f8e390f4.png)

**Comment by ardeay** [comment]
```
Unhandled Runtime Error
Error: MUI: The data grid component requires all rows to have a unique `id` property.
Alternatively, you can use the `getRowId` prop to specify a custom id for each row.
A row was provided without id in the rows prop:
{"ZUID":"5-44ccc74-XXXXX","address":"XXXXX@zesty.io","name":null,"verificationCode":null,"verificationCodeExpiry":null,"emailSent":null,"responseReceived":"2018-06-13T15:40:09Z","createdAt":"2018-06-13T15:40:09Z","updatedAt":"2018-06-13T15:40:09Z","id":null}
```
