### ISSUE TITLE
Instances: Overview Page

### ISSUE THREAD

**Issue by ardeay** [zesty-io/nextjs-website#894]
Overview page of each instance's page

**Comment by ardeay** [comment]
@bltarkany please paste a screenshot of your overview page design for instances. @darwin808 please implement @bltarkany designs

**Comment by bltarkany** [comment]
![image](https://user-images.githubusercontent.com/50595614/186745813-37271670-40e9-4f60-b9bd-c5ee7ffc2c1c.png)

**Comment by ardeay** [comment]
@bltarkany is this screenshot intended to be the main dashboard?

**Comment by bltarkany** [comment]
@ardeay it was meant to replace the blue area here so that there is no dead space(image below). With the new layout changes, it doesn't work well there unless it starts with an overview of the instance and has release updates below it. And unless there are tabs there really isn't a way to include status.zesty.io. 
![image](https://user-images.githubusercontent.com/50595614/187452341-f41b624e-cf0b-42ff-8e31-92dcf94ee55e.png)

**Comment by bltarkany** [comment]
Updated Overview wireframe for current layout - instance specific:
![image](https://user-images.githubusercontent.com/50595614/187496835-32953a0c-732e-4077-ae05-8dbb557a8b50.png)
