### ISSUE TITLE
Instances APIs View

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/nextjs-website#966]
- Include all auto generated APIs with documentation links and explanations of each

**Comment by giseleblair** [comment]
@bltarkany please include list of all api's required for this view

**Comment by bltarkany** [comment]
@glespinosa this is referring to Webengine Mode endpoints

Documentation can be found here:
https://zesty.org/services/web-engine/modes#change-webengine-mode

https://zesty.org/apis/json-endpoints

the Instant API endpoints are reliant on the Basic JSON API setting set to on - the zuid below is instance specific and will be different for each instance:
![image](https://user-images.githubusercontent.com/50595614/189739545-4aedbf1f-f597-4ebc-ab29-48b7add8539f.png)

**update setting endpoint:**
https://instances-api.zesty.org/#9db975df-8f8b-4a6a-b820-2d684a5e0da3
 
**payload from my test instance showing instant API update setting payload**
```
ID: 8
ZUID: "29-fefcfae0db-58679m"
admin: null
category: "developer"
createdAt: "2018-08-13T22:55:57Z"
dataType: "checkbox"
key: "basic_content_api_enabled"
keyFriendly: "Access to Basic JSON API for content."
options: "0,1"
parsleyAccess: null
tips: ""
updatedAt: "2021-09-09T16:58:56Z"
value: "1"
```

all of the other endpoints are reliant on the webengine mode setting set to Headless or Hybrid:
![image](https://user-images.githubusercontent.com/50595614/189740176-edcce180-017a-4bb0-a30a-0c72211e247f.png)

**update setting endpoint:**
https://instances-api.zesty.org/#9db975df-8f8b-4a6a-b820-2d684a5e0da3

Once the setting is turned on you can go to the /-/headless/ endpoint of the instance. Which is structured using the instance's domain followed by the endpoint. For example, below is the headless endpoint to my test instance - I sent you an invite to the instance so that you can see the results:
https://photoblog.zesty.dev/-/headless/
